githubteacher/developers-jun-2016-emea

- arvsharm.md
> Added a new file by arvsharm

- jaszhou-Sydney.md
This PR is to add Sydney to the list of cities
> jaszhou adds hometown of Sydney

- Indonesia.md
- Yes.md
- ariestiyansyah-indonesia.md
- ariestiyansyah.md
Pull Request from ariestiyansyah Indonesia
> Ariestiyansyah adds hometown of Indonesia

- WilliamRClark-Southbridge.md
What kind of activities are people interested in in NewEngland?
> WilliamRClark adds hometown of Southbridge

- jakeruss-capecoral.md
This pull request is to add Cape Coral to cities
> Added local attraction to cape coral readme

- barrburd-MadisonNJ.md
This PR is to add Madison NJ to the list of cities in the repo.
Some questions I want answered are:
- Is anyone else having trouble thinking of anything to attract people to their home town?
- Is everyone else getting flooded with emails even though they unsubscribed?
> barryburd adds hometown of Madison NJ

- Crackedbeaker-Rathfriland.md
This PR is to add Rathfriland to the list of "cities" - it's a small town...
Questions
- Do we even have tourist attractions?
> Crackedbeaker adds hometown of Rathfriland

- pa101-delhi.md
This PR is to add delhi to the list of cities in the class repo.
Some question i want answered:-
> pa101 adds hometown of delhi

- cartucciam-Rome.md
This pull request is to add Rome to the list of cities.
> cartucciam adds hometown of Rome

- Feterovsky-Raleigh.md
That is the list of cool restaurants in Raleigh
Please answer to:
- Is there any tourist attractions in Piedmont area?
> Feterovsky adds hometown of Raleigh

- wmiller9-walker.md
This PR is to add Walker to the list of cities in the class repo.
Some questions:
- Has anyone been to Northern Minnesota?
- Anyone interested in fishing, sailing, water skiing?
> wmiller9 adds hometown of Walker

- YOUR_USERNAME-YOUR_TOWN.md
This PR is to add Orlando to the list of cities in the class repo.
Some questions I want answered are:
- Does anyone come to Central Florida looking for a particular type of food? 
- Is Central Florida synonymous with theme parks? Or are folks interested in natural attractions, as well?
> YOUR_USERNAME adds hometown of YOUR_HOMETOWN

- RobMaskell-Winchester.md
This PR is to add Winchester to the list of cities in the class repo.
Questions:
- Does anyone come to Winchester looking for anything in particular?
- Types of food?
- Transport?
> RobMaskell adds hometown of Winchester

- jspaezp-Bogota.md
This PR is to add Bogota to the class repo
Collaboration: 
- Let me know what you would like me to add to the atractions
- add any cool places you know
> jspaezp adds hometown of Bogota

- Redfire2001-westford.md
This PR is to add Westford to the list of cities in the class repo.
- Which types of restaurants should I add--Asian or Pizza places?
- Should I add more indoor activites, outdoor activities, or both?
> Redfire2001 adds hometown of Westford

- gitalinoe_NewJersey.md
> gitalinoe commented new attraction lists

- Rhebel-GreenBay.md
This PR adds Green Bay.
Does anybody ever go to GB outside of football games? Why?
> Rhebel adds hometown of Green Bay

- Daveyaki-BishopsStortford2.md
testing - sorry missed a step and it went wrong
> Daveyaki bishops stortford

- cobrien-dev-Boston.md
This PR is to add Boston to the list of cities in the class repo.
Questions:
- Are there any extra categories people would like?
- What sort of food do people like?
- Indoor or outdoor activities?
> cobrien-dev adds hometown of Boston

- stephen-murby-manchester.md
PR to add Manchester, UK as a city to the repository.
> stephen-murby adds hometown of Manchester, UK.

- awgregory-jacksonville.md
The PR is to add Jacksonville to list of cities in class repo
Do people look for food while in town?
> awgregory adds hometown of Jacksonville

- setgetme-Wroclaw.md
This RP is to add Wroclaw to the list of cities in the class repo.
Q:
- what restaurant do u suggest?
> setgetme adds hometown of Wroclaw

- govin-lala-philly.md
What's the best place to dine in Philly ?
> First version of govin-lala-philly.md checked in.

- hlmuludiang-philadelphia.md
This pull request is to add Philadelphia to the list of cities
> hlmuludiang adds hometown of philadelphia

- koffi-test.md
- koffisani-libreville.md
This PR is to add Libreville to the list of cities in class repo.
Some questions I want answered are : 
- Does anyone come to Libreville looking for a particular type of food ?
- Is Libreville synonymous with theme parks ? Or are folks insterested innatural attractions, as well ?
> koffisani adds hometown of Libreville

- iampiyushgupta-Mumbai.md
This PR is to add Mumbai to the list of cities in the class repo,
I don't have any questions .. :smile:
> iampiyushgupta adds hometown of Mumbai

- marcellom_berlin.md
This PR is to add Berlin to the list of cities in the class repo.
The questions I want to answer are:
- Does anyone want to visit Berlin and know about attractions?
> marcellom adds hometown of Berlin

- johnrc-centerton.md
This PR is to add Centerton to the list of cities in the class repo.
Some questions:
* Does anyone come to Centerton, Arkansas to eat BBQ?
> johnrc adds hometown of Centerton

- file2.md
This PR is to add Columbus to the list of cities in the Class Repo.
> RaghavT adds hometown of Columbus

- hiseni-minsk.md
> add postal code

- marlyna93-Szeged.md
This PR is to add Szeged to the list of the cities in the class repo.
Some questions I want answered here:
- Does anyone came to Hungary looking for a particular type of food?
- Or are folks interested in natural attractions?
> Marlyna93 adds hometown of Szeged

- arvsharm.md
> A new modification by arvsharm

- govin-lala-philly.md
All: What do you like to know more about Philly 🚗 
@iampiyushgupta Did you visit Philly 
This PR closes #50
> govin-lala : Added more attractions

- Crackedbeaker-Rathfriland.md
> Crackedbeaker adds tourist attraction to Rathfriland

- Feterovsky-Raleigh.md
added NC state as tourist attraction
This PR closes #48
> Feterovsky added NC State as tourist attraction

- jakeruss-capecoral.md
Added a tourist attraction
This PR closes #163
> Add a tourist attraction

- Daveyaki-BishopsStortford.md
@AnwarAli364 can you check this for me [London](http://bbc.co.uk)
> inline comment - added attraction

- WilliamRClark-Southbridge.md
All: What attractions would you want to visit?
This pr closes #160
> WilliamRClark Makes Southbridge seem more attractive

- wmiller9-walker.md
> wmiller9 adds additional tourist attraction to Walker 

- YOUR_USERNAME-YOUR_TOWN.md
All: what are some things you'd like to know about visiting Central Florida? 🌊  🐭 
@brianamarie have you ever been to Florida? Is there a theme park that you might be interested in knowing about? 
@crichid do you think I have enough things for kids to do on my hometown file? 
@beardofedu any good recommendations for breweries? 
This PR closes #159
> YOUR_USERNAME adds tourist attractions to YOUR_TOWN

- RobMaskell-Winchester.md
Do these tourist attractions look interesting?
This PR closes #165
> RobMaskell add some tourist attractions to Winchester

- Rhebel-GreenBay.md
Are there other nearby places people want to visit?
> Rhebel add nearby places

- awgregory-jacksonville.md
Added beach.  Didn't mention waffle house [http://www.wafflehouse.com/]
This PR closes #139
> awgregory added attraction to jacksonville

- marcellom_berlin.md
Moved the local attractions to tourists attractions, and added a local attraction.
Added the local attraction Berlin Spree river
This pull request closes #183
> Added local attraction and changed previous tourist attractions

- stephen-murby-manchester.md
All: Does anyone need anything specific while on their visit?
> Added possible tourist attractions to my town.

- cobrien-dev-Boston.md
@guramipal  should I add more North End restaurants?
@WilliamRClark do your kids like museums?
> Add restaurants to boston

- InesBelhouchet-Tunisia.md
Tunisia is a nice country, who want to visit it?
> InesBelhouchet add Hometown to Tunisia 

- Redfire2001-westford.md
Are there other types of restaurants that I should add? 
This PR closes #164.
> Redfire2001 adds another attraction to Westford file

- cartucciam-Rome.md
All: what are some things you'd like to know about visiting Italy? 🍷 🍝 🍦 
This PR closes #44
> cartucciam adds tourist attraction to Rome

- hlmuludiang-philadelphia.md
All: Anyone know any local attractions?
The PR closes #190
> Added a couple local attractions

- guramipal-Natick.md
@cobrien-dev  have you visit Natick Common?
This PT closes #10
> add attractions

- iampiyushgupta-Mumbai.md
> iampiyushgupta adds tourist attraction to Mumbai

- barrburd-MadisonNJ.md
> Added my town's many tourist attractions

- rvm-bulgaria.md
Does anyone was in Sandanski, Bulgaria, it is a popular tourists destination
> rvm-bulgaria adds something rvm-bulgaria

- cjsrinivas-morrisville.md
Has anyone visited Morrisville, NC ?
> cjsrinivas adds hometown of morrisville

- AmirNewFile2
- Amir_ForkingNew
> merge request
